language: node_js
node_js: 
  - 10
services:
  - docker
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - cd frontend; yarn; yarn build; cd ..
  - docker build -t boxmein/kfst-boat-visualizer .

deploy:
  provider: script
  script: bash sh/ci-deploy-to-docker-hub.sh
  on:
    branch: master
